<?php

    return [
        'colors' => [
            'red' => 'red',
            'orange' => 'orange',
            'green' => 'green',
        ],
        'transition_words' => [
            'in the first place',
            'but also',
            'as a matter of fact',
            'in like manner',
            'in addition',
            'coupled with',
            'in the same fashion',
            'in the same way',
            'in the light of',
            'not to mention',
            'to say nothing of',
            'equally important',
            'by the same token',
            'equally',
            'identically',
            'moreover',
            'as well as',
            'together with',
            'of course',
            'likewise',
            'comparatively',
            'correspondingly',
            'similarly',
            'furthermore',
            'additionally',
            'although this may be true',
            'in contrast',
            'different from',
            'on the other hand',
            'on the contrary',
            'in spite of',
            'even so',
            'though',
            'be that as it may',
            'then again',
            'above all',
            'in reality',
            'after all',
            'but',
            'still',
            'unlike',
            'while',
            'albeit',
            'besides',
            'as much as',
            'though',
            'instead',
            'whereas',
            'despite',
            'conversely',
            'otherwise',
            'however',
            'than',
            'rather',
            'nevertheless',
            'nonetheless',
            'regardless',
            'notwithstanding',
            'in the event that',
            'so long as',
            'for the purpose of',
            'with this intention',
            'with this in mind',
            'in the hope that',
            'to the end that',
            'for fear that',
            'in order to',
            'seeing that',
            'being that',
            'in view of',
            'unless',
            'whenever',
            'while',
            'because of',
            'since',
            'while',
            'lest',
            'in case',
            'provided that',
            'given that',
            'only if',
            'even if',
            'so that',
            'so as to',
            'owing to',
            'inasmuch as',
            'due to',
            'in other words',
            'to put it differently',
            'for one thing',
            'as an illustration',
            'in this case',
            'for this reason',
            'to put it another way',
            'that is to say',
            'with attention to',
            'by all means',
            'important to realize',
            'another key point',
            'first thing to remember',
            'most compelling evidence',
            'must be remembered',
            'point often overlooked',
            'to point out',
            'on the positive side',
            'on the negative side',
            'with this in mind',
            'to be sure',
            'chiefly',
            'indeed',
            'certainly',
            'surely',
            'markedly',
            'such as',
            'especially',
            'explicitly',
            'specifically',
            'surprisingly',
            'significantly',
            'particularly',
            'in general',
            'in particular',
            'in detail',
            'for example',
            'for instance',
            'to demonstrate',
            'to emphasize',
            'to repeat',
            'to clarify',
            'to explain',
            'to enumerate',
            'as a result',
            'under those circumstances',
            'in that case',
            'for this reason',
            'in effect',
            'thus',
            'because the',
            'then',
            'consequently',
            'therefore',
            'thereupon',
            'accordingly',
            'as can be seen',
            'generally speaking',
            'in the final analysis',
            'all things considered',
            'as shown above',
            'in the long run',
            'given these points',
            'as has been noted',
            'in a word',
            'for the most part',
            'in fact',
            'in summary',
            'in conclusion',
            'in short',
            'in brief',
            'in essence',
            'to summarize',
            'on balance',
            'altogether',
            'overall',
            'by and large',
            'to sum up',
            'on the whole',
            'in any event',
            'in either case',
            'all in all',
            'obviously',
            'at the present time',
            'from time to time',
            'sooner or later',
            'at the same time',
            'up to the present time',
            'to begin with',
            'in due time',
            'as soon as',
            'as long as',
            'in the meantime',
            'without delay',
            'in the first place',
            'all of a sudden',
            'at this instant',
            'finally',
            'later',
            'last',
            'until',
            'till',
            'before',
            'hence',
            'since',
            'when',
            'once',
            'formerly',
            'shortly',
            'henceforth',
            'eventually',
            'meanwhile',
            'further',
            'during',
            'in time',
            'prior to',
            'forthwith',
            'straightaway',
            'by the time',
            'whenever',
            'until now',
            'now that',
            'presently',
            'occasionally',
        ],
        'passive_voice' => [
            'verbs' => [
                  'am',
                  'are',
                  'were',
                  'being',
                  'is',
                  'been',
                  'was',
                  'be',
                  'have',
            ],
            'past_participle_verbs' => [
                  'awoken',
                  'awoke',
                  'beaten',
                  'beat',
                  'begun',
                  'began',
                  'bent',
                  'bitten',
                  'bit',
                  'bled',
                  'blown',
                  'blew',
                  'broken',
                  'broke',
                  'brought',
                  'built',
                  'bought',
                  'caught',
                  'chosen',
                  'chose',
                  'dealt',
                  'done',
                  'did',
                  'drawn',
                  'drew',
                  'driven',
                  'drove',
                  'eaten',
                  'ate',
                  'fed',
                  'felt',
                  'fought',
                  'found',
                  'forbidden',
                  'forbade',
                  'forgotten',
                  'forgot',
                  'forgiven',
                  'forgave',
                  'frozen',
                  'froze',
                  'gotten',
                  'got',
                  'given',
                  'gave',
                  'ground',
                  'grinded',
                  'hung',
                  'heard',
                  'hidden',
                  'hid',
                  'hit',
                  'held',
                  'hurt',
                  'kept',
                  'known',
                  'knew',
                  'laid',
                  'led',
                  'let',
                  'lost',
                  'made',
                  'meant',
                  'met',
                  'paid',
                  'proven',
                  'proved',
                  'put',
                  'read',
                  'ridden',
                  'rode',
                  'rung',
                  'rang',
                  'run',
                  'ran',
                  'said',
                  'seen',
                  'saw',
                  'sold',
                  'sent',
                  'shaken',
                  'shook',
                  'shaved',
                  'shot',
                  'shown',
                  'shut',
                  'sung',
                  'sunk',
                  'slain',
                  'slew',
                  'slid',
                  'spoken',
                  'spoke',
                  'spent',
                  'spun',
                  'split',
                  'spread',
                  'stolen',
                  'stole',
                  'struck',
                  'swept',
                  'swung',
                  'taken',
                  'took',
                  'taught',
                  'torn',
                  'tore',
                  'told',
                  'thought',
                  'thrown',
                  'threw',
                  'undergone',
                  'underwent',
                  'understood',
                  'upset',
                  'woken',
                  'woke',
                  'worn',
                  'wore',
                  'won',
                  'withdrawn',
                  'withdrew',
                  'written',
                  'wrote',
                  'been',
                  'born',
                  'become',
                  'beset',
                  'bet',
                  'bid',
                  'bidden',
                  'bound',
                  'bred',
                  'broadcast',
                  'burnt',
                  'burst',
                  'cast',
                  'clung',
                  'come',
                  'cost',
                  'crept',
                  'cut',
                  'dug',
                  'dived',
                  'dreamt',
                  'drunk',
                  'fallen',
                  'fit',
                  'fled',
                  'flung',
                  'flown',
                  'foregone',
                  'forsaken',
                  'gone',
                  'grown',
                  'knelt',
                  'knit',
                  'leapt',
                  'learnt',
                  'left',
                  'lent',
                  'lain',
                  'lighted',
                  'misspelt',
                  'mistaken',
                  'mown',
                  'overcome',
                  'overdone',
                  'overtaken',
                  'overthrown',
                  'pled',
                  'quit',
                  'rid',
                  'risen',
                  'sawn',
                  'sought',
                  'set',
                  'sewn',
                  'shaven',
                  'shorn',
                  'shed',
                  'shone',
                  'shod',
                  'shrunk',
                  'sat',
                  'slept',
                  'slung',
                  'slit',
                  'smitten',
                  'sown',
                  'sped',
                  'spilt',
                  'spit',
                  'sprung',
                  'stood',
                  'stuck',
                  'stung',
                  'stunk',
                  'stridden',
                  'strung',
                  'striven',
                  'sworn',
                  'swollen',
                  'swum',
                  'thrived',
                  'thrust',
                  'trodden',
                  'upheld',
                  'woven',
                  'wed',
                  'wept',
                  'wound',
                  'withheld',
                  'withstood',
                  'wrung',
            ],
        ],
        'image_fields' => [
              'seo_social_image' => [
                  'thumbnails' => [
                      'admin' => [
                          'width' => 400,
                          'height' => 210,
                          'type' => 'resize',
                      ],
                      'normal' => [
                          'width' => 600,
                          'height' => 315,
                          'type' => 'resize',
                      ],
                  ],
              ],
              'seo_facebook' => [
                  'thumbnails' => [
                      'admin' => [
                          'width' => 400,
                          'height' => 210,
                          'type' => 'resize',
                      ],
                      'normal' => [
                          'width' => 600,
                          'height' => 315,
                          'type' => 'resize',
                      ],
                  ],
              ],
              'seo_twitter' => [
                  'thumbnails' => [
                      'admin' => [
                          'width' => 400,
                          'height' => 210,
                          'type' => 'resize',
                      ],
                      'normal' => [
                          'width' => 512,
                          'height' => 256,
                          'type' => 'resize',
                      ],
                  ],
              ],
          ],
    ];
